repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: ''
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: ''
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: ''
  hooks:
  - id: flake8